<?php
echo '<tr><td>Cutomer ID</td>';
echo '<td>';
echo $row['customer_id']  ;
echo '</td>';
echo "</tr>";
echo '<tr><td>Name</td>';
echo '<td>';
echo $row['name']  ;
echo '</td>';
echo "</tr>";
echo '<tr><td> NIC</td>';
echo '<td>';
echo $row['nic']  ;
echo '</td>';
echo "</tr>";
echo '<tr><td>Email</td>';
echo '<td>';
echo $row['Email']  ;
echo '</td>';
echo "</tr>";
echo '<tr><td>Gender</td>';
echo '<td>';
echo $row['gender']  ;
echo '</td>';
echo "</tr>";
echo '<tr><td>Address </td>';
echo '<td>';
echo $row['Address']  ;
echo '</td>';
echo "</tr>";
echo '<tr><td>City</td>';
echo '<td>';
echo $row['City']  ;
echo '</td>';
echo "</tr>";
echo '<tr><td>Phone Number</td>';
echo '<td>';
echo $row['PhoneNo']  ;
echo '</td>';
echo "</tr>";
?>